### ISSUE TITLE
Doesn’t work in foundry 0.7.5

### ISSUE THREAD

**Issue by smilligan93** [smilligan93/combatready#20]
Told it doesn't work, error with importing TweenMax

**Comment by NirodhaAvidya** [comment]
It seems to work for me.
World: D&D5e
Mod list:
about-time--v0.1.58;
actually-private-rolls--v0.2;
autocomplete-whisper--v0.2.0;
CautiousGamemastersPack--v0.1.6;
chat-portrait--v0.2.1;
combatready--v1.1.8;
dice-so-nice--v3.0.2;
fpsmeter--v1.0.1;
gm-notes--v0.2;
_mathjs--v7.5.1-fvtt1;
monsterblock--v2.2.2;
pings--v1.2.9;
response-times--v1.0.1;
tidy5e-sheet--v0.2.28;
tidy-ui_game-settings--v0.1.21;
zoom-pan-options--v1.3.8;

**Comment by NuL1F3** [comment]
Not working for me either. Any chance on an update? Or an eta on one?

**Comment by smilligan93** [comment]
@NirodhaAvidya @NuL1F3 how are you running Foundry? As in what OS and are you using the packaged electron app? I think I found it doesn't work in my linux server but it does work for my development setup (windows electron app). 

I'm thinking this may be the problem?

**Comment by NirodhaAvidya** [comment]
@smilligan93 I'm using the Windows installer.

**Comment by Norc** [comment]
I'm using Windows 10 self hosted electron app, i get the tween max error also.  It could be due to electron versioning... there were changes that may not always apply. Ignorantly this feels like it might be Greensock-related, which is Electron version dependent:

Here is the error:
![image](https://user-images.githubusercontent.com/64667579/97364508-8ae0d800-187a-11eb-843e-30c096f9082b.png)

**Comment by NuL1F3** [comment]
Just Windows 10. Was running perfectly before I updated to 0.7.5. I ran a game before the update, I didn't realise how great this mod was at improving the overall experience of combat until after I updated and didn't have it anymore! From one of the posts above I suspect another mod or mods might be the problem?

**Comment by NuL1F3** [comment]
Good morning Norc, I am an absolute n00b at all things D&D. Could you please tell me how you opened the console? I have not been able to figure that out or find documentation on it.

**Comment by cswendrowski** [comment]
@NuL1F3 F12

**Comment by NuL1F3** [comment]
Awesome! Thank you so much 👍

**Comment by NuL1F3** [comment]
I don't seem to be getting any such error? I'm not getting any messages in regards to CombatReady at all?

**Comment by Norc** [comment]
Look for errors in general, make sure errors are set to display in the console.

Also make sure that you have the module enabled... it should display the TweenMax error when load completes.

**Comment by smilligan93** [comment]
Thank you all for your help! We figured out what the issue is. It's a fairly large API change so it's going to take some time to fix this

**Comment by smilligan93** [comment]
Pushed a very-hot fix to at least get the module loading. Going to close this since it's , please open issues as you see errors come up!

**Comment by NuL1F3** [comment]
It's working again! Thank you :)

**Comment by Norc** [comment]
Confirmed working, thanks for the fix!!!
